### ISSUE TITLE
[Innotech]当设备调成颜色时，只能控制一次开关。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#1]
Android：5.1.0.7359
FW:1.6
描述：当设备调成颜色时，控制开关控制不了。
复现步骤：
1：进入设备详情页面，点击颜色按钮调成蓝色。
2：返回设备详情页面控制设备开关。
3：设备只能控制一次，再控制控制不了。

**Comment by HCfInGE** [comment]
1.6.33版本，用dangle控制没有这种情况。

**Comment by huangzanshan** [comment]
ios:5.2.2(189)
Android：7739
验证通过
