### ISSUE TITLE
[Innotecth]把设备调成绿色时再控制开关，灯带颜色显示蓝色。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#12]
IOS：5.2.2（186）
FW：1.6
描述：把设备调成绿色时再控制开关，设备颜色显示蓝色。
步骤：
1.点击设备详情页面，点击my colors下面颜色为绿色，点击done。
2.点击设备开关控制，设备显示为蓝色。

**Comment by HCfInGE** [comment]
这个颜色保持，需要等待5秒之后，控制开关才能保持上一个颜色。在1.6.33版本已修复。

**Comment by huangzanshan** [comment]
FW：1.7
IOS：5.2.2（188）
5秒之后还是显示蓝色，此问题在这版本还存在。

**Comment by HCfInGE** [comment]
dangle 控制正常

**Comment by huangzanshan** [comment]
这个测灯带时没有升级就开始测，升级后测没有这个问题。
