### ISSUE TITLE
[Innotecth]断电设备，点击删除设备后，上电设备，设备进入复位状态。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#13]
IOS：5.2.2（186）
Andriod:5.1.0.7359
FW：1.6
描述：断电设备，点击删除设备后，上电设备，设备进入复位状态。
步骤：
1.设备在app上可以正常控制后，断电设备，点击删除设备.
2.删除成功，上电设备，设备闪3次进入复位状态。
3.点击扫描搜索设备可以添加进app。

**Comment by WanderingDominic** [comment]
认为是正常现象。
