### ISSUE TITLE
innotech]设备颜色为RGB颜色，再控制亮度滑条，设备有亮度有抖动状态。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#16]

**Comment by huangzanshan** [comment]
IOS：5.2.2（189）
Android：7739
FW：V1.8.38
描述：设备颜色为RGB颜色，再控制亮度滑条，设备亮度有抖动状态。
步骤：
1.设备设备颜色为RGB颜色，滑动亮度滑条。
2.观察设备状态，设备亮度随着滑条移动有抖动状态。

**Comment by huangzanshan** [comment]
IOS：5.2.2（189）
FW：1.8.38
描述：设备颜色为RGB颜色，再控制亮度滑条，设备有亮度有抖动状态。 
步骤：
1.设置设备颜色为RGB颜色，点击保存，再控制亮度滑条。
2.观察设备状态，设备随着控制滑条有抖动状态。

**Comment by WanderingDominic** [comment]
新的PVP样品没有此问题。请使用1.8.40和PVP样品复测。
