### ISSUE TITLE
[innotech]灯处于蓝色，重新调整灯处于绿色，断电再上电设备，设备颜色变成蓝色。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#25]
Android：7739
FW：1.8.38
描述：灯设置了颜色系数后，重新上电，颜色系数未起作用，需要重新切换下颜色。
步骤：
1.灯处于蓝色，重新调整灯处于绿色，断电再上电设备，设备颜色变成蓝色。

**Comment by HCfInGE** [comment]
修改灯的状态，要保持5s后才能保存

**Comment by WanderingDominic** [comment]
保存状态需要延迟时间5S，是正常现象。
