### ISSUE TITLE
[innotech]安卓手机点击扫描设备，没有点击done自动添加进来，再扫描设备还能扫描到。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#27]
Android：7778
FW：1.8.39
描述：安卓手机点击扫描设备，没有点击done自动添加进来，再扫描设备还没扫描到。
步骤：
1.点击添加设备，点击扫描设备，扫描到设备后点击返回键按钮，在设备列表上能看到设备已经添加进来，2.在本手机上点击扫描，还能扫描得到。
3.在另一个手机上不再扫描得到。

**Comment by HCfInGE** [comment]
如果没点击done，直接返回，这种情况需要APP发送kick out 指令，因为灯已经入网了。

**Comment by WanderingDominic** [comment]
认为是正常情况。
