### ISSUE TITLE
[innotech]设备添加进app，在app上点击设备控制开关，一个设备开关能控制两个设备。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#28]
Android：7778
FW：1.8.39
描述：设备添加进app，在app上点击设备控制开关，一个设备开关能控制两个设备。
步骤：
1.设备成功添加进app。在app上点击设备，能控制两个设备。
2.过一分钟后正常控制，即点击一个设备开关能控制一个设备。

**Comment by WanderingDominic** [comment]
Dangle测试没有问题，无法复现此现象。请问用APP时该现象是偶然出现还是？

**Comment by huangzanshan** [comment]
偶然遇到一次。
