### ISSUE TITLE
[innotech]两个灯带，其中一个灯带删除后或复位后再扫描添加时很难扫描得到。

### ISSUE THREAD

**Issue by huangzanshan** [JasonTian2018/RGBW-bulb-strip#32]
ios:5.2.2(189)
FW：1.8.39
描述：在色盘上把颜色调到黄色点击done,再控制设备开关，设备显示冷光。

**Comment by huangzanshan** [comment]
IOS：5.2.2（189）
FW：1.8.39
描述：两个灯带，其中一个灯带删除后或复位后再扫描添加时很难扫描得到。

**Comment by huangzanshan** [comment]
这个问题是接连电源的那个板块问题造成的，用其他正常的板块是没有这个问题。

**Comment by HCfInGE** [comment]
硬件问题
